public enum FarmOptions
{
    PRINT_MENU, ADD_FARM, ADD_SHED, ADD_SHED_CUSTOM, SHOW_MILKTANK_FREESPACE, ADD_DAIRYCOW, ADD_GOAT, ADD_BEEFCOW, ADD_SHEEP, REMOVE_DAIRYCOW, REMOVE_GOAT,
    REMOVE_BEEFCOW, REMOVE_SHEEP,  MILK_DAIRYCOW, MILK_ALL_DAIRYCOW, MILK_GOAT, MILK_ALL_GOAT, COLLECT_MILK, PRINT_ANIMALS, QUIT;
}
